### ISSUE TITLE
Error Writing Settings File

### ISSUE THREAD

**Issue by a1o1** [apolakipso/FormatRadio#1]
Answering Machine Recordings (1.4G) Seems to work perfectly but ALL other choices result in the following:

> > > Creating source dir ./output/29-dark-dub/source
> > > Downloading "358 free dark dub samples (379MB)" from http://cdn.mos.musicradar.com/audio/samples/musicradar-dark-dub-samples.zip into "./output/29-dark-dub/source/29-dark-dub.zip"
> > > Skipping creating target dir, "./output/29-dark-dub" already exists
> > > Unzipping "./output/29-dark-dub/source/29-dark-dub.zip"
> > > Mode: spreadAcrossVolumes
> > > Set contains 358 files
> > > Traceback (most recent call last):
> > >   File "create.py", line 322, in <module>
> > >     main()
> > >   File "create.py", line 250, in main
> > >     writeSettings("%s/%s-%d/%s" % (targetFolder, key, currentVolume, SETTINGS_FILE), settings)
> > >   File "create.py", line 134, in writeSettings
> > >     with open(path, 'w') as f:
> > > IOError: [Errno 2] No such file or directory: u'./output/29-dark-dub/29-dark-dub-0/settings.txt'

**Comment by d1al0g** [comment]
I've been getting the same issue.

I created the file myself and it worked a little better, but eventually crashed everytime for a similar error.

edit: here's the error I've gotten after creating the settings file myself

`Traceback (most recent call last):
  File "create.py", line 322, in <module>
    main()
  File "create.py", line 309, in main
    writeSettings("%s/%s-%d/" % (targetFolder, key, currentVolume), settings)
  File "create.py", line 134, in writeSettings
    with open(path, 'w') as f:
IOError: [Errno 21] Is a directory: u'./output/20-ambient/20-ambient-0/'
Users-MacBook-Pro-2:FormatRadio-master User$ 
`

**Comment by jeremybernstein** [comment]
Same here
